name = input("Please enter your name: ")
age = input("How old are you?: ")
print(name)
print("Squeeky: Yo whats up world it's ya girl Squeeky amen and amen again!!!")
print(f"{name}:yo whats up world today we at wendys trying out the new chicken fires burger")
print("Squeeky: OHHH WEEE!")
print(f"{name}: Let's get our grace on yo.")
print("Squeeky: Amen and amen again")
print(f"{name}: Lets dig in")
print("Squeeky: OOOOHHH WEEEE")
print(": whats up world")
